[tool.poetry]
name = "product"
description = "The product service"
package-mode = false


[tool.poetry.dependencies]
python = "^3.12"
fastapi = {extras = ["standard"], version = "^0.115.12"}
celery = "^5.3.0"
redis = "^5.0.0"
psycopg = "^3.1.0"
watchdog = "^6.0.0"