[tool.poetry]
name = "accounting"
description = "The accounting service"
package-mode = false


[tool.poetry.dependencies]
python = "^3.12"
celery = "^5.3.0"
redis = "^5.0.0"
watchdog = {extras = ["watchmedo"], version = "^6.0.0"}
